Stabilized existing implementation of magnetic Fresnel computation
scgmlz/BornAgain pull request #1043
Opened 2020-09-07 15:47 UTC by rbeerwerth

This PR provides an enhanced numerical stability of the existing implementation of the polarized Fresnel computation. This method is unchanged and as described in the document theory/polarizedSpecular. 
The modification applied in the last commit is described in Section 4 of that document. 
With these changes, the numerical precision is enhanced for samples with more than a few layers as long as all the the layers are not too thick. Due to the rotation of the polarization there is still a significant loss of precision if the layer thickness becomes too large.
The first three commits do minor changes, also in preparation of the new polarized computational kernel, that will supersede this implementation. Even though this implementation will likely not be used in the future it still makes sense to update it, in order to facilitate testing of the new implementation, and especially the Fresnel coefficients.

Additional external testing was performed to verify these changes.

2020-09-08 11:20 UTC, gpospelov commented on Core/Computation/SpecularComputationTerm.h
> +                     const ISpecularStrategy::coefficient_pointer_type& coeff) const;
`pointer&` looks a bit embarrassing for me. I wouldn't encode type inside the definition, this would simplify switching to something different later on (std::variant). Are you using `coefficient_type` anywhere else? One could use `using coefficient_type = std::unique_ptr<const ILayerRTCoefficients>;`. This all of course is minor.

2020-09-08 11:26 UTC, gpospelov approved these changes

2020-09-08 11:26 UTC, gpospelov commented on Core/RT/MatrixRTCoefficients_v2.h
> +    friend class SpecularMagnetic_v3ConsistencyTest_ScalarMagneticAmplitudes_Test;
I recon, it is temporary solution?

2020-09-08 11:59 UTC, rbeerwerth commented on Core/Computation/SpecularComputationTerm.h
> +                     const ISpecularStrategy::coefficient_pointer_type& coeff) const;
hmm, not entirely sure how you mean this. It would still be an aliases smart pointer, right? Maybe we should avoid these aliases anyhow a bit more...

2020-09-08 12:00 UTC, rbeerwerth commented on Core/RT/MatrixRTCoefficients_v2.h
> +    friend class SpecularMagnetic_v3ConsistencyTest_ScalarMagneticAmplitudes_Test;
yes and now... it was a leftover, i removed it. thanks!

2020-09-11 07:19 UTC, jwuttke requested changes

2020-09-11 07:19 UTC, jwuttke commented on Core/Multilayer/SpecularMagneticStrategy.cpp
> +        auto S = std::get<0>(r);
I'd prefer `r.first` over `get<0>`, as it lets me at least guess that `r` is a `pair`. But why not go for C++17 structured binding: Instead of lines 197-199, just `const auto [SMatrix, norm] = findNormalizationCoefficients(coeff[i]);`

2020-09-11 07:19 UTC, jwuttke commented on Core/Multilayer/SpecularMagneticStrategy.cpp
> +    auto d1 = S(1, 1) - S(0, 1);
explicit type, please (double or complex_t ?). And `const` whereever possible.

2020-09-11 07:19 UTC, jwuttke commented on Core/Multilayer/SpecularScalarStrategy.h
> +    using coefficient_type         = ScalarRTCoefficients;
What's the advantage of this and the following alias? It's hardly shorter than the right hand side.

2020-09-11 07:19 UTC, jwuttke commented on Core/RT/ILayerRTCoefficients.h
> +    virtual Eigen::Matrix2cd getReflectionMatrix() const
Can this be moved to the parent class? Always raise NotImplemented unless defined in child class.

2020-09-11 07:19 UTC, jwuttke commented on Core/Basics/Complex.h
> +constexpr complex_t I = complex_t(0.0, 1.0);
Not sure about this. Discounting the cases where `exp_I` can be used, I feel there are not enough explicit uses of `I` in the code to justify this ultrashort global variable.

2020-09-11 07:19 UTC, jwuttke commented on Core/Multilayer/SpecularMagneticStrategy.h
> +    using coefficient_type = MatrixRTCoefficients_v2;
same comment as below (SpecularScalarStrategy.h): is there strong enough an advantage to justify two extra aliases?

2020-09-11 07:43 UTC, rbeerwerth commented on Core/Multilayer/SpecularMagneticStrategy.h
> +    using coefficient_type = MatrixRTCoefficients_v2;
yep, i needed it in external tests

2020-09-11 12:24 UTC, merged