Refactor output data read write
scgmlz/BornAgain pull request #1129
Opened 2020-12-02 20:00 UTC by mpuchner

Refactored reader and writer for OutputData. A longer explanation about the design motivation is contained in the commits.

2020-12-02 21:46 UTC, jwuttke requested changes
Looks very good, thank you. Let's discuss tomorrow how to deal with comments.

2020-12-02 21:46 UTC, jwuttke commented on Device/InputOutput/OutputDataReadReflectometry.cpp
> +    std::map<double, double> QvsR;
Prompted me to write http://apps.jcns.fz-juelich.de/redmine/issues/2508, but not your problem here.

2020-12-02 21:46 UTC, jwuttke commented on Device/InputOutput/OutputDataReadWriteINT.h
> +};
This needs oral discussion, I guess. Why not leave details like the `precision` in the anonymous namespace in the cpp file?

2020-12-02 21:46 UTC, jwuttke commented on Device/Histo/IntensityDataIOFactory.cpp
> +
Nice solution. But what about splitting the steps data -> stringstream and stringstream -> file? The first step in the if-construct, but without need for lambdas, returning a stringstream; then the second step regardless of format.

2020-12-03 06:28 UTC, mpuchner commented on Device/InputOutput/OutputDataReadWriteNumpyTXT.cpp
> +    } else if (ncols < 2) {
This is copy&paste from the original code. Wanted to keep senior-member-code as much 1:1 as possible... 
I will change this

2020-12-03 06:29 UTC, mpuchner commented on Device/InputOutput/OutputDataReadWriteNumpyTXT.cpp
> +        }
This is copy&paste from the original code. Wanted to keep senior-member-code as much 1:1 as possible... 
I will change this

2020-12-03 06:29 UTC, mpuchner commented on Device/Histo/IntensityDataIOFactory.cpp
> +    std::stringstream ss;
This is copy&paste from the original code. Wanted to keep senior-member-code as much 1:1 as possible... 
I will think about it

2020-12-03 06:30 UTC, mpuchner commented on Device/InputOutput/OutputDataReadWriteTiff.cpp
> +        throw std::runtime_error("OutputDataReadWriteTiff::read() -> Can't open the file.");
This is copy&paste from the original code. Wanted to keep senior-member-code as much 1:1 as possible... 
So I let this be for now, and wait for the more general rework

2020-12-03 06:30 UTC, mpuchner commented on Device/InputOutput/OutputDataReadWriteTiff.h
>  //!
I will change this

2020-12-03 06:36 UTC, mpuchner commented on Device/InputOutput/OutputDataReadWriteINT.h
> +};
The idea was complete encapsulation and grouping (involved members/vars/consts as well as information). This value is used in a class member, therefore IMHO it should be also a class member itself. But I am open to different solutions. Let's discuss it as you suggested

2020-12-03 06:38 UTC, mpuchner commented on Device/Histo/IntensityDataIOFactory.cpp
> +
Indeed I had it implemented like you suggest, but it looked asymmetric to me in regards to the read implementation... I can rework it

2020-12-03 06:53 UTC, jwuttke commented on Device/Histo/IntensityDataIOFactory.cpp
> +
If you see no comparable solution for the read case, then better leave both as they are, as symmetry/analogy is a strong argument.

2020-12-03 06:58 UTC, jwuttke commented on Device/InputOutput/OutputDataReadWriteINT.h
> +};
In other places in the code the output floating-point precision is hard coded. So let's eliminate that variable for good. Then two private functions can become static, if I remember correctly.

2020-12-04 14:38 UTC, mpuchner commented on Device/Histo/IntensityDataIOFactory.cpp
> +    std::stringstream ss;
ostringstream is not possible since it is used later on as iostream

2020-12-04 15:03 UTC, mpuchner commented on Device/Histo/IntensityDataIOFactory.cpp
> +
I didn't find a nice solution. I leave it unchanged.

2020-12-04 15:49 UTC, merged