fix "Crash on saving to deleted project"
scgmlz/BornAgain pull request #1135
Opened 2020-12-05 08:54 UTC by mpuchner

Please read the commit comment for details

2020-12-05 17:13 UTC, jwuttke requested changes

2020-12-05 17:13 UTC, jwuttke commented on GUI/coregui/utils/GUIHelpers.cpp
>  }
We should use this opportunity to further improve the legacy code.  The actual action (mkdir) should not be encapsulated by tests for anomalous conditions. Rather somewhat like
```
ASSERT(projectDir.exists());
if (!projectDir.exists(subdirName))
    throw ...
bool success = projectDir.mkdir(subdirName));
if (!success)
     throw ...
```
Choose throw vs ASSERT depending on whether or not the condition can be triggered by bad user input.

2020-12-07 09:33 UTC, mpuchner commented on GUI/coregui/utils/GUIHelpers.cpp
>  }
Reworked the dependencies so this code became obsolete

2020-12-07 11:09 UTC, jwuttke commented on GUI/coregui/utils/GUIHelpers.cpp
>  }
even better, thank you

2020-12-07 11:28 UTC, jwuttke approved these changes

2020-12-07 11:39 UTC, merged