Correct handling of polarization
scgmlz/BornAgain pull request #1217
Opened 2021-02-22 10:39 UTC by rbeerwerth

This PR corrects the handling of polarization.
* Fixes the problem reported #1200: If an analyzer is set now the polarized engine is utilized even when the sample itself is non-magnetic. This ensures that the spin-flip intensity vanishes, as expected.
* This applies to reflectometry as well as scattering on particles
* Also problems when changing the of some initialization of the beam parameters is fixed.

This needs independent validation.

2021-02-22 11:46 UTC, jwuttke commented on Core/Simulation/ISimulation.cpp
> +    m_options.setIsPolarized(true);
What if a user calls simulation.detector().setAnalyzerProperties instead of simulation.setAnalyzerProperties?
Generally, we are converting towards indirect calls; we should rather remove ISimulation::setAnalyzerProperties for good.
So need a different mechanism to replace the proposed ISimulation::m_options.

2021-02-22 11:49 UTC, jwuttke commented on Sample/RT/SimulationOptions.h
> +    bool m_is_polarized;
As far as I see, the other member variables are user choices whereas m_is_polarized caches information deduced from other settings.

2021-02-22 11:54 UTC, rbeerwerth commented on Sample/RT/SimulationOptions.h
> +    bool m_is_polarized;
Not sure what you mean by user choices. But `simulation.getOptions().setUseAvgMaterials(True)` sets `m_use_avg_materials`.

2021-02-22 11:56 UTC, jwuttke requested changes
Fix of #1200 is highly appreciated.
However, let's clearly distinguish user-chosen options and cached derived information; and keep analyzer properties out of Simulation classes.

2021-02-22 12:04 UTC, jwuttke commented on Sample/RT/SimulationOptions.h
> +    bool m_is_polarized;
Maybe use_avg_materials should also be simplified?

2021-02-23 09:37 UTC, rbeerwerth commented
closing.
New clean PR in preparation

2021-02-23 09:37 UTC, closed without merging